import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const read = (path: string) => readFileSync(resolve(process.cwd(), path), 'utf8')

describe('LINE pickup notification edge functions', () => {
  it('authenticates the Supabase user and organizer role before service-role recipient access', () => {
    const source = read('supabase/functions/_shared/sendPickupNotification.ts')
    const productionEntry = read('supabase/functions/send-pickup-notification/index.ts')
    const testEntry = read('supabase/functions/send-test-pickup-notification/index.ts')
    const getUser = source.indexOf('.auth.getUser(')
    const adminCheck = source.indexOf(".rpc('is_admin')")
    const recipients = source.indexOf(".rpc('internal_pickup_notification_recipients'")

    expect(getUser).toBeGreaterThan(-1)
    expect(adminCheck).toBeGreaterThan(getUser)
    expect(recipients).toBeGreaterThan(adminCheck)
    expect(source).toContain(".rpc('is_admin')")
    expect(source).toContain(".rpc('is_approved_line_organizer')")
    expect(source).toContain(".rpc('reserve_pickup_notification_intent'")
    expect(source).toContain(".rpc('inspect_pickup_notification_intent'")
    expect(source).toContain(".rpc('claim_pickup_notification_intent'")
    expect(source).toContain(".rpc('mark_pickup_notification_intent_sent'")
    expect(source).toContain('p_caller_user_id: userData.user.id')
    expect(source).toContain('PICKUP_NOTIFICATION_INTENT_SECRET')
    expect(productionEntry).toContain("createPickupNotificationHandler('production')")
    expect(testEntry).toContain("createPickupNotificationHandler('test')")
    expect(source).not.toContain('body.destination')
    expect(source).toContain('sealedSnapshot.destination !== destination')
    expect(source).toContain('p_binding_kind: destination')
    expect(source).toContain('sealPickupRecipientSnapshot')
    expect(source).toContain('openPickupRecipientSnapshot')
    expect(source).toContain("intentState?.delivery_status === 'sending'")
    expect(source).toContain('sealedSnapshot.lineUserIds')
    expect(source).toContain("'X-Line-Retry-Key': intent.line_retry_key")
    const reserve = source.indexOf(".rpc('reserve_pickup_notification_intent'")
    const lineMembers = source.indexOf('await getLineGroupMemberIdsForCandidates')
    expect(reserve).toBeGreaterThan(-1)
    expect(lineMembers).toBeGreaterThan(reserve)
    expect(source).not.toContain(".from('pickup_notification_intent')")
    expect(source).toContain('pickupRecipientSnapshotHash')
    expect(source).toContain('pickupEligibleRecipientSnapshotHash')
    expect(source).toContain('p_eligible_hash: eligibleHash')
    expect(source).toContain('p_line_group_id: groupId')
    expect(source).toContain('previewToken')
    expect(source).toContain('getLineGroupMemberIdsForCandidates')
    expect(source).not.toContain('getLineGroupMemberIds(')
    expect(source).toContain("message.startsWith('無法確認LINE群組成員')")
    expect(source).toContain('buildPickupMentionMessages')
    expect(source).toContain("startsWith('【測試】\\n')")
    expect(source).toContain("destination === 'test'")
    expect(source).toContain("action === 'send'")
    expect(source).toContain('mentionableRecipients: mentionable.map(publicRecipient)')
    const sentShortcut = source.indexOf("intentState.delivery_status === 'sent'")
    const markerLookup = source.indexOf(".from('pickup_notification_test_campaign')")
    const messageHash = source.indexOf('const messageHash = await technicalSha256(message)')
    const inspect = source.indexOf(".rpc('inspect_pickup_notification_intent'")
    expect(sentShortcut).toBeGreaterThan(-1)
    expect(messageHash).toBeGreaterThan(-1)
    expect(inspect).toBeGreaterThan(messageHash)
    expect(source).toContain('p_message_hash: messageHash')
    expect(source).not.toContain('technicalSha256(message.trim())')
    expect(markerLookup).toBeGreaterThan(sentShortcut)
    const publicMapper = source.slice(source.indexOf('function publicRecipient'), source.indexOf('export function createPickupNotificationHandler'))
    expect(publicMapper).not.toContain('line_user_id')
  })

  it('verifies the LINE signature and binds a group only from an approved organizer command', () => {
    const source = read('supabase/functions/line-group-webhook/index.ts')
    expect(source).toContain('verifyLineWebhookSignature')
    expect(source).toContain('webhookEventId')
    expect(source).toContain('process_line_group_binding_event')
    expect(source).toContain('timestamp')
    expect(source).toContain('綁定測試團購通知')
    expect(source).toContain('綁定正式團購通知')
    expect(source).not.toContain("const BIND_COMMAND = '綁定團購通知'")
    expect(source).toContain('p_binding_kind: bindingKind')
    expect(source).toContain(".rpc('process_line_group_binding_event'")
    expect(source).not.toContain(".from('line_webhook_event_replay')")
    expect(source).not.toContain(".from('line_organizer_identity')")
    expect(source).not.toContain(".from('admin_users')")
    expect(source).not.toContain(".from('community_line_group')")
    expect(source).toContain('AbortSignal.timeout')
  })

  it('disables Supabase JWT verification only for the LINE-signed webhook', () => {
    const config = read('supabase/config.toml')
    expect(config).toMatch(/\[functions\.line-group-webhook\]\s*verify_jwt = false/)
    expect(config).toMatch(/\[functions\.send-pickup-notification\]\s*verify_jwt = true/)
    expect(config).toMatch(/\[functions\.send-test-pickup-notification\]\s*verify_jwt = true/)
  })
})
