-- Restrict campaign image objects to the one-level path shape generated by
-- the application. This prevents nested objects from evading campaign cleanup.

create or replace function public.campaign_image_path_is_live(p_name text)
returns boolean
language plpgsql
volatile
security definer
set search_path = public, pg_temp
as $$
declare
  v_campaign_id uuid;
begin
  if not public.is_admin() then
    return false;
  end if;
  if p_name !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|jpeg|png|webp)$' then
    return false;
  end if;

  v_campaign_id := split_part(p_name, '/', 1)::uuid;
  perform pg_advisory_xact_lock(hashtextextended(v_campaign_id::text, 0));

  return exists (
    select 1
    from public.campaign c
    where c.id = v_campaign_id
  );
end;
$$;

revoke all on function public.campaign_image_path_is_live(text)
from public, anon;
grant execute on function public.campaign_image_path_is_live(text)
to authenticated, service_role;
